### ISSUE TITLE
Mehrere Kategorien

### ISSUE THREAD

**Issue by Minihockey** [At3flo/swiss-hockey-tool#20]
Is it possible to register more than one category for one tournament? I think there would be too much tournaments if only one category is shown by its own.

Look for the example of HC Lahr. 

Would be easier if I could choose more than one category and even for each category there would be the button Availability of places for each category.
The button Open tournament is thought for? If all places are full? When it is like this it only make sense to set more than one category.

What do you think?

**Comment by matbgn** [comment]
The idea was proposed from Mathias if I remember correctly. The all mechanics works on a single tournament subscritption but I will figure out how to handle this.

**Comment by matbgn** [comment]
> The button Open tournament is thought for? If all places are full? When it is like this it only make sense to set more than one category.

It's more a legacy from the old system, as far as I understood the tournament could be closed by the organizer right ?

**Comment by matbgn** [comment]
Resolved with #23
