### ISSUE TITLE
Button availability

### ISSUE THREAD

**Issue by Minihockey** [At3flo/swiss-hockey-tool#29]
Hi Matthieu,

ist auch eine dritte Gruppe möglich? Wir wollen zwar maximal zwei Kategorien, aber das war auf das Alter bezogen. Habe gerade das Finalturnier am 20.06.2020 in Wettingen eingegeben und dort soll man zwischen U12 Elite, U12 Challenge und U12 Girls entscheiden können. Bräuchte da also sogar einen dritten grünen Button. Möglich oder eher nicht?

Gruss, Kerstin

**Comment by matbgn** [comment]
Yes, Just add it and it will be directly available. ;-)
