### ISSUE TITLE
Namen

### ISSUE THREAD

**Issue by Minihockey** [At3flo/swiss-hockey-tool#36]
Do we can change the name from Swiss Hockey Tool into 
Swiss Hockey Kids Tool?

**Comment by Minihockey** [comment]
Oh nein, die Seite ist ja fix "gekauft", also registriert online unter Swiss Hockey Tool, oder?

Dachte, ich könnte noch den Bogen zu den Hockeykids schaffen, aber das war wohl nix.

**Comment by matbgn** [comment]
Ja, und die Tatsache, dass die U15 und die Möglichkeit, Senioren leicht hinzuzufügen, machen den Namen Swiss Hockey Tool besser für zukünftige Entwicklungen geeignet.
