### ISSUE TITLE
Kategorie auf Front

### ISSUE THREAD

**Issue by Minihockey** [At3flo/swiss-hockey-tool#39]
Kann man statt der Startzeit (die könnte man sehr gut auch im Kommentar anzeigen, da man wegen den Zeiten eh genau schauen muss, siehe 25.08.2019 in Basel)
auch die Kategorie auf die Startseite stellen? Also in den Spalten:
Datum
Kategorie
Feld
Veranstalter
Ort
Kontakt
Teams

Die Kategorie wäre nur der Übersichtlichkeit wegen,d ass man dort sofort sieht, für wen das Turnier ist.

Gruss, Kerstin

**Comment by matbgn** [comment]
There is not enough place to do it in an oneline style. If a tournament have three categories for instance everything will become ugly. E.g. with U10 Challenge + U12 Challenge + U15 Challenge it's too long.

Two solutions: 
1° I remove the start time
2° You decide with Paul and others what you want exactly for columns, but it will in any way cost new development time. Depending on demand 3-4 hours. So it mean a new request for offer.

Give me a feed back when decided and feel free to reopen this ticket to keep track of discussion.

**Comment by Minihockey** [comment]
Ok, we've to talk about. Think especialy in the juniors forum.
