### ISSUE TITLE
Turnierstatus

### ISSUE THREAD

**Issue by Minihockey** [At3flo/swiss-hockey-tool#40]
Wenn der Turnierstatus/tournament state auf geschlossen/closed gesetzt wird, ist es weiterhin möglich, sich anzumelden.

Sinn? Das sollte doch so etwas wie der Meldeschluss sein, oder?

**Comment by Minihockey** [comment]
Und wenn Turnierstatus auf geschlossen, dann müssten auch die Kategorien auf rot gesetzt werden, damit man sieht, dass das voll/geschlossen ist.

**Comment by matbgn** [comment]
Closed with 0.6.2-beta
