### ISSUE TITLE
Zu viele Mannschaften

### ISSUE THREAD

**Issue by Minihockey** [At3flo/swiss-hockey-tool#41]
Schaue bitte mal bei dem Testturnier am 28.06.2020

Dort konnte Ralf statt der angegebenen 5 Mannschaften 8 Mannschaften anmelden.

**Comment by Minihockey** [comment]
Hier die Erklärung von Ralf dazu:
Zum Zähler, der verrutscht ist, braucht Matthieu sicher eine bessere Beschreibung, was ich gemacht habe.
 
1 - Turnier angelegt, Kategorie U10 Challenge mit vier Teams
 
2 - zwei Teams für die Kategorie U10 Challenge angemeldet - Zähler zeigt 2/4 -> korrekt
 
3 - Turnier editiert, Kategorie U10 Challenge gelöscht - U10 Challenge wird nicht mehr angezeigt -> korrekt
 
4 - Turnier editiert, Kategorie U10 Challenge wieder hinzugefügt - Zähler auf 6/6 -> eigentlich korrekt, allerdings tauchen lustigerweise die beiden Teams wieder auf, die ich unter 2 angemeldet hatte -> also doch nicht korrekt
 
5 - sechs Teams für die Kategorie U10 Challenge angemeldet - Zähler zeigt 0/6 und Kategorie ausgebucht -> korrekt
 
6 - Turnier editiert, Anzahl Teams für Kategorie U10 Challenge auf 5 reduziert - Zähler nun -1/5, sechs Teams werden aufgelistet (also acht inkl. der zwei aus Schritt 2, die in 4 wieder aufgetaucht sind) -> nicht korrekt bzw. nicht sehr intuitiv

**Comment by matbgn** [comment]
It's a known bug, but the steps to reproduce it are so tricky (multiple inscriptions trashed by the organisator) new ones created afterward...

The workaround for now is to ask an admin to clean the tournament by removing unwanted teams.

If it's really needed to solve this issue I kindly ask for a new request of offer. Time roughly counted 5 to 10 hours to do things properly.

**Comment by Minihockey** [comment]
Ok, if it was only once that more teams were able to register than possible, there is no problem for the moment. We'll look for.
