### ISSUE TITLE
Anmeldung/add a new tournament

### ISSUE THREAD

**Issue by Minihockey** [At3flo/swiss-hockey-tool#42]
Nächster Faux-pas:

siehe 30.06.2020

ZSHT/Zürichsee Hockey Team kann für jeden beliebigen Club ein Turnier eröffnen.
Dann allerdings nicht bearbeiten. Was ja korrekt ist.

Das sollte natürlich nicht möglich sein.

**Comment by matbgn** [comment]
In the Database I see that it's the user with id 7 that last edited (created ?) this tournament. Correct ?

Here the raw data :

```
#<Event:0x0000000007a98e20
 id: 54,
 date: Tue, 30 Jun 2020,
 start_time: Sat, 01 Jan 2000 06:45:00 UTC +00:00,
 location: "Ein weiteres Testturnier",
 contact: "Ralf Korinth, +4177 445 2172, ralf.korinth@gmx.de",
 is_tournament_open: true,
 is_outdoor: true,
 other_informations: "Ein weiteres Testturnier",
 club_id: 25,
 user_id: 7,
 created_at: Thu, 25 Jul 2019 13:54:55 UTC +00:00,
(...)
```

Where user id = 7 is you :

```
#<User id: 7, email: "championship@swisshockey.org", created_at: "2019-06-27 17:07:35", updated_at: "2019-07-18 05:46:11", first_name: "Kerstin", last_name: "Szymkowiak", phone_number: "+4177 477 2128", role: "admin", club_id: 1>
```

I will look deeper in this bug.

**Comment by matbgn** [comment]
It's Ok I found how to reproduce the bug thx

**Comment by matbgn** [comment]
Closed with bugfix 0.6.2-beta
